name: Daily Cinema Calendar Update

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'movie_scraper/**'
      - '.github/workflows/**'

jobs:
  update-calendar:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install project with deps
      run: |
        set -euo pipefail
        python -m pip install --upgrade pip
        pip install -e . || true
        pip install aiohttp beautifulsoup4 lxml icalendar python-dateutil pytz aiosqlite pydantic pydantic-settings structlog tenacity httpx

    - name: Ensure docs dir exists
      run: mkdir -p docs

    - name: Run scraper and generate calendar (diagnostic mode)
      env:
        PYTHONPATH: .
        MOVIE_SCRAPER_LOG_LEVEL: DEBUG
      run: |
        set -euo pipefail
        python -c "
        import asyncio, sys
        sys.path.insert(0, '.')
        from movie_scraper.simple_scraper import main
        asyncio.run(main())
        "

    - name: Show DIAG COPY block
      if: always()
      run: |
        echo "--- DIAG COPY ---"
        if [ -f docs/diag.txt ]; then tail -n 100 docs/diag.txt; else echo "no diag.txt"; fi
        echo "--- END DIAG ---"

    - name: Deploy to GitHub Pages (main/docs)
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
