name: Daily Cinema Calendar Update

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'movie_scraper/**'
      - '.github/workflows/**'

jobs:
  update-calendar:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: main
        persist-credentials: true
        fetch-depth: 0

    - name: Setup Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install project with deps
      run: |
        set -euo pipefail
        python -m pip install --upgrade pip
        pip install -e . || true
        pip install aiohttp beautifulsoup4 lxml icalendar python-dateutil pytz aiosqlite pydantic pydantic-settings structlog tenacity httpx

    - name: Ensure docs and data dir exist
      run: |
        mkdir -p docs
        mkdir -p data

    - name: Run scraper and generate calendar (limit=5)
      env:
        PYTHONPATH: .
        MOVIE_SCRAPER_LOG_LEVEL: DEBUG
        MOVIE_SCRAPER_MAX_FILMS: "5"
        MOVIE_SCRAPER_RATE_LIMIT: "5.0"
      run: |
        set -euo pipefail
        python -m py_compile movie_scraper/simple_scraper.py
        python -c "
        import asyncio, sys
        sys.path.insert(0, '.')
        from movie_scraper.simple_scraper import main
        asyncio.run(main())
        "

    - name: Show DIAG COPY block
      if: always()
      run: |
        echo "--- DIAG COPY ---"
        if [ -f docs/diag.txt ]; then tail -n 200 docs/diag.txt; else echo "no diag.txt"; fi
        echo "--- END DIAG ---"

    - name: List docs artifacts
      if: always()
      run: |
        ls -la docs || true
        test -f docs/calendar.ics && echo "ICS_OK" || echo "ICS_MISS"
        test -f docs/index.html && echo "INDEX_OK" || echo "INDEX_MISS"

    - name: Commit and push docs to main (for Pages main/docs)
      if: github.ref == 'refs/heads/main'
      run: |
        set -euo pipefail
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git pull --ff-only
        git add docs/
        if git diff --staged --quiet; then
          echo "No changes in docs to commit"
        else
          git commit -m "Update cinema calendar docs (index.html, calendar.ics, diag.txt)"
          git push origin HEAD:main
        fi
